### PR TITLE
Update readme.md_Vivian Li

### PR DESCRIPTION
**Pull request by yl1250**
## 🎯 Objective

_Note why you're making this change and any relevant issues_: Updated the breakfast recipe with a fruit granola recipe 🍓 

## 🛠️ Changes made

_Note what you actual changes you're proposing_ : Updated the recipe with a name, serving size, ingredients, time to prepare, equipments, and steps.

## 👥 Who needs to review this Pull Request?: @ShogoYakame @jainaman93 @SophonWhisperer 

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Review by yl1250 — COMMENTED** [review]
@neiloneill let me know if you don't see the changes to the breakfast recipe. Thanks!

**Review by neiloneill — APPROVED** [review]
Don't know what cantaloupe is, but sounds good!

**Review by yl1250 — COMMENTED** [review]
I have removed the goji berries to this recipe since not everyone likes that! Also added another step to the preparation which is to mix the ingredients. 👍

**Review by tommasodvc — APPROVED** [review]
Sounds good!

**Review by ShogoYakame — COMMENTED** [review]
Thank you for making it! love this!

**Pull request merged**
